import "server-only";
import { AuthorizationError,getAuthenticatedUserId,requireOrganizationRole } from "@/lib/auth/server";
import { attachmentInputSchema } from "@/lib/rfqs/validation";
import { createClient } from "@/lib/supabase/server";
import type { AppRole,Database } from "@/lib/supabase/types";
import type { PurchaseOrderAttachmentDTO,PurchaseOrderDetailsDTO,PurchaseOrderHistoryDTO,PurchaseOrderItemDTO,PurchaseOrderListDTO } from "./authorization";
import { createPurchaseOrderSchema,draftUpdateSchema,purchaseOrderIdSchema,purchaseOrderItemSchema,type CreatePurchaseOrderInput,type PurchaseOrderItemInput } from "./validation";
const managers:readonly AppRole[]=["owner","admin","operations","purchasing"],readers:readonly AppRole[]=[...managers,"inspection","finance"];
type PO=Database["public"]["Tables"]["purchase_orders"]["Row"]; type Item=Database["public"]["Tables"]["purchase_order_items"]["Row"]; type Attachment=Database["public"]["Tables"]["rfq_attachments"]["Row"]; const fail=(e:unknown)=>{if(e)throw new AuthorizationError("ROLE_REQUIRED")};
const list=(r:PO):PurchaseOrderListDTO=>({id:r.id,purchaseOrderNumber:r.purchase_order_number,versionNumber:r.version_number,rfqId:r.rfq_id,rfqItemId:r.rfq_item_id,supplierId:r.supplier_id,status:r.status,currency:r.currency,orderDate:r.order_date,expectedDeliveryDate:r.expected_delivery_date,createdAt:r.created_at});
const detail=(r:PO):PurchaseOrderDetailsDTO=>({...list(r),supplierCandidateId:r.supplier_candidate_id,supplierSelectionId:r.supplier_selection_id,quotationId:r.quotation_id,incoterm:r.incoterm,paymentTerms:r.payment_terms,supplierReference:r.supplier_reference,internalNotes:r.internal_notes,supplierNotes:r.supplier_notes,approvedBy:r.approved_by,approvedAt:r.approved_at,cancelledAt:r.cancelled_at,archivedAt:r.archived_at,updatedAt:r.updated_at});
const item=(r:Item):PurchaseOrderItemDTO=>({id:r.id,purchaseOrderId:r.purchase_order_id,rfqItemId:r.rfq_item_id,quotationItemId:r.quotation_item_id,quantity:Number(r.quantity),unit:r.unit,unitPrice:Number(r.unit_price),currency:r.currency,lineTotal:Number(r.line_total),productDescription:r.product_description,moq:r.moq===null?null:Number(r.moq),agreedLeadTimeDays:r.agreed_lead_time_days,packagingNotes:r.packaging_notes,supplierNotes:r.supplier_notes,internalNotes:r.internal_notes,createdAt:r.created_at});
const attachment=(r:Attachment):PurchaseOrderAttachmentDTO=>({id:r.id,purchaseOrderId:r.owner_id,originalFilename:r.original_filename,contentType:r.content_type,fileSize:Number(r.file_size),createdAt:r.created_at});
export async function createPurchaseOrderFromSelection(org:string,input:CreatePurchaseOrderInput):Promise<PurchaseOrderDetailsDTO>{await requireOrganizationRole(org,managers);const v=createPurchaseOrderSchema.parse(input);const {data,error}=await createClient().rpc("create_purchase_order_from_selection",{target_organization_id:org,target_supplier_selection_id:v.supplierSelectionId,target_order_date:v.orderDate,target_expected_delivery_date:v.expectedDeliveryDate??null,target_supplier_reference:v.supplierReference??null,target_internal_notes:v.internalNotes??null,target_supplier_notes:v.supplierNotes??null});fail(error);const r=data?.[0];if(!r)throw new AuthorizationError("ROLE_REQUIRED");return detail(r)}
export async function updateDraftPurchaseOrder(org:string,id:string,input:unknown):Promise<PurchaseOrderDetailsDTO>{await requireOrganizationRole(org,managers);const v=draftUpdateSchema.parse(input);const {data,error}=await createClient().from("purchase_orders").update({expected_delivery_date:v.expectedDeliveryDate,supplier_reference:v.supplierReference,internal_notes:v.internalNotes,supplier_notes:v.supplierNotes}).eq("organization_id",org).eq("id",id).eq("status","draft").select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return detail(data)}
async function transition(org:string,id:string,status:"approved"|"issued"|"cancelled"|"archived"):Promise<PurchaseOrderDetailsDTO>{await requireOrganizationRole(org,managers);const uid=await getAuthenticatedUserId();if(!uid)throw new AuthorizationError("UNAUTHENTICATED");const patch=status==="approved"?{status,approved_by:uid,approved_at:new Date().toISOString()}:status==="cancelled"?{status,cancelled_at:new Date().toISOString()} : status==="archived"?{status,archived_at:new Date().toISOString()}:{status};const {data,error}=await createClient().from("purchase_orders").update(patch).eq("organization_id",org).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");const event=status==="approved"?"purchase_order_approved":status==="issued"?"purchase_order_issued":status==="cancelled"?"purchase_order_cancelled":null;if(event)await createClient().from("rfq_activity_events").insert({organization_id:org,rfq_id:data.rfq_id,rfq_item_id:data.rfq_item_id,event_type:event,title:event.replaceAll("_"," "),description:null,visibility:"internal",actor_user_id:uid,metadata:{purchase_order_id:data.id}});return detail(data)}
export const approvePurchaseOrder=(o:string,id:string)=>transition(o,id,"approved"); export const issuePurchaseOrder=(o:string,id:string)=>transition(o,id,"issued"); export const cancelPurchaseOrder=(o:string,id:string)=>transition(o,id,"cancelled"); export const archivePurchaseOrder=(o:string,id:string)=>transition(o,id,"archived");
export async function createPurchaseOrderRevision(org:string,purchaseOrderId:string,notes?:{internalNotes?:string;supplierNotes?:string}):Promise<PurchaseOrderDetailsDTO>{await requireOrganizationRole(org,managers);const {data,error}=await createClient().rpc("create_purchase_order_revision",{target_organization_id:org,target_purchase_order_id:purchaseOrderId,target_internal_notes:notes?.internalNotes??null,target_supplier_notes:notes?.supplierNotes??null});fail(error);const row=data?.[0];if(!row)throw new AuthorizationError("ROLE_REQUIRED");return detail(row)}
export async function getPurchaseOrder(org:string,id:string):Promise<PurchaseOrderDetailsDTO>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("purchase_orders").select().eq("organization_id",org).eq("id",id).single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return detail(data)} export async function listPurchaseOrders(org:string):Promise<PurchaseOrderListDTO[]>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("purchase_orders").select().eq("organization_id",org).is("archived_at",null);fail(error);return(data??[]).map(list)} export async function listPurchaseOrdersForRFQ(org:string,rfq:string):Promise<PurchaseOrderListDTO[]>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("purchase_orders").select().eq("organization_id",org).eq("rfq_id",rfq).is("archived_at",null);fail(error);return(data??[]).map(list)} export async function listPurchaseOrderHistory(org:string,number:string):Promise<PurchaseOrderHistoryDTO[]>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("purchase_orders").select().eq("organization_id",org).eq("purchase_order_number",number).order("version_number",{ascending:false});fail(error);return(data??[]).map(detail)}
export async function addPurchaseOrderItem(org:string,po:string,input:PurchaseOrderItemInput):Promise<PurchaseOrderItemDTO>{await requireOrganizationRole(org,managers);const v=purchaseOrderItemSchema.parse(input);const {data,error}=await createClient().from("purchase_order_items").insert({organization_id:org,purchase_order_id:po,rfq_item_id:v.rfqItemId,quantity:v.quantity,unit:v.unit,unit_price:v.unitPrice,currency:v.currency,product_description:v.productDescription??null,moq:v.moq??null,agreed_lead_time_days:v.agreedLeadTimeDays??null,packaging_notes:v.packagingNotes??null,supplier_notes:v.supplierNotes??null,internal_notes:v.internalNotes??null}).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return item(data)}
export async function updatePurchaseOrderItem(org:string,id:string,input:PurchaseOrderItemInput):Promise<PurchaseOrderItemDTO>{await requireOrganizationRole(org,managers);const v=purchaseOrderItemSchema.parse(input);const {data,error}=await createClient().from("purchase_order_items").update({quantity:v.quantity,unit:v.unit,unit_price:v.unitPrice,product_description:v.productDescription??null,moq:v.moq??null,agreed_lead_time_days:v.agreedLeadTimeDays??null,packaging_notes:v.packagingNotes??null,supplier_notes:v.supplierNotes??null,internal_notes:v.internalNotes??null}).eq("organization_id",org).eq("id",id).is("archived_at",null).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return item(data)}
export async function archivePurchaseOrderItem(org:string,id:string):Promise<PurchaseOrderItemDTO>{await requireOrganizationRole(org,managers);const {data,error}=await createClient().from("purchase_order_items").update({archived_at:new Date().toISOString()}).eq("organization_id",org).eq("id",id).is("archived_at",null).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return item(data)}
export async function addPurchaseOrderAttachmentMetadata(org:string,input:unknown):Promise<PurchaseOrderAttachmentDTO>{await requireOrganizationRole(org,managers);const uid=await getAuthenticatedUserId();if(!uid)throw new AuthorizationError("UNAUTHENTICATED");const v=attachmentInputSchema.parse(input);if(v.ownerType!=="purchase_order"||v.visibility!=="internal")throw new AuthorizationError("ROLE_REQUIRED");const {data,error}=await createClient().from("rfq_attachments").insert({organization_id:org,owner_type:"purchase_order",owner_id:v.ownerId,storage_bucket:v.storageBucket,storage_path:v.storagePath,original_filename:v.originalFilename,content_type:v.contentType,file_size:v.fileSize,visibility:"internal",uploaded_by:uid}).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return attachment(data)}
export async function archivePurchaseOrderAttachmentMetadata(org:string,id:string):Promise<PurchaseOrderAttachmentDTO>{await requireOrganizationRole(org,managers);const {data,error}=await createClient().from("rfq_attachments").update({archived_at:new Date().toISOString()}).eq("organization_id",org).eq("id",id).eq("owner_type","purchase_order").select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return attachment(data)}
