import "server-only";
import { AuthorizationError, requireOrganizationRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import type { AppRole } from "@/lib/supabase/types";
import type { CandidateDetailsDTO, CandidateListDTO } from "./authorization";
import { candidateInputSchema, type CandidateInput } from "./validation";
const managers:readonly AppRole[]=["owner","admin","operations","purchasing"]; const readers:readonly AppRole[]=[...managers,"inspection","finance"];
const mapList=(r:{id:string;rfq_item_id:string;supplier_id:string;candidate_status:string;assigned_to_profile_id:string|null;created_at:string}):CandidateListDTO=>({id:r.id,rfqItemId:r.rfq_item_id,supplierId:r.supplier_id,candidateStatus:r.candidate_status,assignedToProfileId:r.assigned_to_profile_id,createdAt:r.created_at});
const mapDetails=(r:{id:string;rfq_item_id:string;supplier_id:string;candidate_status:string;assigned_to_profile_id:string|null;internal_notes:string|null;created_at:string;updated_at:string}):CandidateDetailsDTO=>({...mapList(r),internalNotes:r.internal_notes,updatedAt:r.updated_at});
const fail=(e:unknown)=>{if(e)throw new AuthorizationError("ROLE_REQUIRED")};
export async function createCandidate(org:string,input:CandidateInput):Promise<CandidateDetailsDTO>{await requireOrganizationRole(org,managers);const v=candidateInputSchema.parse(input);const {data,error}=await createClient().from("supplier_candidates").insert({organization_id:org,rfq_item_id:v.rfqItemId,supplier_id:v.supplierId,candidate_status:v.candidateStatus,assigned_to_profile_id:v.assignedToProfileId??null,internal_notes:v.internalNotes??null,archived_at:v.archivedAt??null}).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return mapDetails(data)}
export async function updateCandidate(org:string,id:string,input:CandidateInput):Promise<CandidateDetailsDTO>{await requireOrganizationRole(org,managers);const v=candidateInputSchema.parse(input);const {data,error}=await createClient().from("supplier_candidates").update({candidate_status:v.candidateStatus,assigned_to_profile_id:v.assignedToProfileId??null,internal_notes:v.internalNotes??null,archived_at:v.archivedAt??null}).eq("organization_id",org).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return mapDetails(data)}
export async function archiveCandidate(org:string,id:string):Promise<CandidateDetailsDTO>{await requireOrganizationRole(org,managers);const {data,error}=await createClient().from("supplier_candidates").update({candidate_status:"archived",archived_at:new Date().toISOString()}).eq("organization_id",org).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return mapDetails(data)}
export async function listCandidatesForRFQItem(org:string,rfqItemId:string):Promise<CandidateListDTO[]>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("supplier_candidates").select("id,rfq_item_id,supplier_id,candidate_status,assigned_to_profile_id,created_at").eq("organization_id",org).eq("rfq_item_id",rfqItemId).is("archived_at",null);fail(error);return(data??[]).map(mapList)}
export async function getCandidate(org:string,id:string):Promise<CandidateDetailsDTO>{await requireOrganizationRole(org,readers);const {data,error}=await createClient().from("supplier_candidates").select("id,rfq_item_id,supplier_id,candidate_status,assigned_to_profile_id,internal_notes,created_at,updated_at").eq("organization_id",org).eq("id",id).single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return mapDetails(data)}
