import "server-only";
import { AuthorizationError, requireOrganizationRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import type { AppRole, SupplierCapability } from "@/lib/supabase/types";
import { certificateInputSchema, supplierContactInputSchema, supplierInputSchema } from "./validation";
import type { InternalSupplierDTO, SupplierCertificateDTO, SupplierContactDTO, SupplierListDTO } from "./authorization";
const managers:readonly AppRole[]=["owner","admin","operations"]; const readers:readonly AppRole[]=[...managers,"purchasing","inspection","finance"];
const fail=(error:unknown)=>{if(error) throw new AuthorizationError("ROLE_REQUIRED")};
const listDto=(r:{id:string;supplier_code:string;legal_name:string;display_name:string;supplier_status:string;verification_status:string;legal_entity_type:string}):SupplierListDTO=>({id:r.id,supplierCode:r.supplier_code,legalName:r.legal_name,displayName:r.display_name,supplierStatus:r.supplier_status,verificationStatus:r.verification_status,legalEntityType:r.legal_entity_type});
const contactDto=(r:{id:string;name:string;position:string|null;email:string|null;phone:string|null;whatsapp:string|null;preferred_language:string|null;is_primary:boolean}):SupplierContactDTO=>({id:r.id,name:r.name,position:r.position,email:r.email,phone:r.phone,whatsapp:r.whatsapp,preferredLanguage:r.preferred_language,isPrimary:r.is_primary}); const certificateDto=(r:{id:string;certificate_type:string;certificate_number:string|null;issuing_body:string|null;issue_date:string|null;expiry_date:string|null}):SupplierCertificateDTO=>({id:r.id,certificateType:r.certificate_type,certificateNumber:r.certificate_number,issuingBody:r.issuing_body,issueDate:r.issue_date,expiryDate:r.expiry_date});
export async function listSuppliers(organizationId:string):Promise<SupplierListDTO[]>{await requireOrganizationRole(organizationId,readers);const {data,error}=await createClient().from("suppliers").select("id,supplier_code,legal_name,display_name,supplier_status,verification_status,legal_entity_type").eq("organization_id",organizationId).is("archived_at",null);fail(error);return (data??[]).map(listDto)}
export async function getSupplier(organizationId:string,id:string):Promise<InternalSupplierDTO>{await requireOrganizationRole(organizationId,readers);const {data,error}=await createClient().from("suppliers").select("id,supplier_code,legal_name,display_name,supplier_status,verification_status,legal_entity_type,notes_internal").eq("organization_id",organizationId).eq("id",id).single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return {...listDto(data),notesInternal:data.notes_internal}}
export async function createSupplier(organizationId:string,input:unknown):Promise<InternalSupplierDTO>{await requireOrganizationRole(organizationId,managers);const v=supplierInputSchema.parse(input);const {capabilities,...s}=v;const {data,error}=await createClient().from("suppliers").insert({organization_id:organizationId,supplier_code:s.supplierCode,legal_name:s.legalName,display_name:s.displayName,supplier_status:s.supplierStatus,verification_status:s.verificationStatus,legal_entity_type:s.legalEntityType,website:s.website??null,email:s.email??null,phone:s.phone??null,whatsapp:s.whatsapp??null,country_code:s.countryCode??null,province:s.province??null,city:s.city??null,address:s.address??null,postal_code:s.postalCode??null,timezone:s.timezone??null,preferred_currency:s.preferredCurrency??null,preferred_language:s.preferredLanguage??null,years_in_business:s.yearsInBusiness??null,employee_count:s.employeeCount??null,annual_capacity_notes:s.annualCapacityNotes??null,notes_internal:s.notesInternal??null,archived_at:s.archivedAt??null}).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");await setSupplierCapabilities(organizationId,data.id,capabilities);return {...listDto(data),notesInternal:data.notes_internal}}
export async function updateSupplier(organizationId:string,id:string,input:unknown){await requireOrganizationRole(organizationId,managers);const v=supplierInputSchema.parse(input);const {data,error}=await createClient().from("suppliers").update({legal_name:v.legalName,display_name:v.displayName,supplier_status:v.supplierStatus,verification_status:v.verificationStatus,legal_entity_type:v.legalEntityType}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);return data}
export async function archiveSupplier(organizationId:string,id:string){await requireOrganizationRole(organizationId,managers);const {data,error}=await createClient().from("suppliers").update({supplier_status:"archived",archived_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);return data}
export async function setSupplierCapabilities(organizationId:string,supplierId:string,capabilities:readonly SupplierCapability[]):Promise<SupplierCapability[]>{await requireOrganizationRole(organizationId,managers);const unique=Array.from(new Set(capabilities));if(unique.length!==capabilities.length||unique.length===0)throw new AuthorizationError("ROLE_REQUIRED");const {data,error}=await createClient().rpc("replace_supplier_capabilities",{target_organization_id:organizationId,target_supplier_id:supplierId,selected_capabilities:unique});fail(error);return data??[]}
export async function createSupplierContact(organizationId:string,supplierId:string,input:unknown){await requireOrganizationRole(organizationId,managers);const v=supplierContactInputSchema.parse(input);const {data,error}=await createClient().from("supplier_contacts").insert({organization_id:organizationId,supplier_id:supplierId,name:v.name,email:v.email??null,phone:v.phone??null,whatsapp:v.whatsapp??null,is_primary:v.isPrimary}).select().single();fail(error);return data}
export async function updateSupplierContact(organizationId:string,id:string,input:unknown):Promise<SupplierContactDTO>{await requireOrganizationRole(organizationId,managers);const v=supplierContactInputSchema.parse(input);const {data,error}=await createClient().from("supplier_contacts").update({name:v.name,position:v.position??null,email:v.email??null,phone:v.phone??null,whatsapp:v.whatsapp??null,preferred_language:v.preferredLanguage??null,is_primary:v.isPrimary,archived_at:v.archivedAt??null}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return contactDto(data)} export async function archiveSupplierContact(organizationId:string,id:string):Promise<SupplierContactDTO>{await requireOrganizationRole(organizationId,managers);const {data,error}=await createClient().from("supplier_contacts").update({archived_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return contactDto(data)}; export async function setPrimarySupplierContact(organizationId:string,id:string):Promise<SupplierContactDTO>{await requireOrganizationRole(organizationId,managers);const db=createClient();const {data:target,error:targetError}=await db.from("supplier_contacts").select("supplier_id").eq("organization_id",organizationId).eq("id",id).single();fail(targetError);if(!target)throw new AuthorizationError("ROLE_REQUIRED");const {error:clearError}=await db.from("supplier_contacts").update({is_primary:false}).eq("organization_id",organizationId).eq("supplier_id",target.supplier_id).eq("is_primary",true);fail(clearError);const {data,error}=await db.from("supplier_contacts").update({is_primary:true}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return contactDto(data)}
export async function createSupplierCertificate(organizationId:string,supplierId:string,input:unknown):Promise<SupplierCertificateDTO>{await requireOrganizationRole(organizationId,managers);const v=certificateInputSchema.parse(input);const {data,error}=await createClient().from("supplier_certificates").insert({organization_id:organizationId,supplier_id:supplierId,certificate_type:v.certificateType,certificate_number:v.certificateNumber??null,issuing_body:v.issuingBody??null,issue_date:v.issueDate??null,expiry_date:v.expiryDate??null,verification_notes:v.verificationNotes??null,archived_at:v.archivedAt??null}).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return certificateDto(data)} export async function updateSupplierCertificate(organizationId:string,id:string,input:unknown):Promise<SupplierCertificateDTO>{await requireOrganizationRole(organizationId,managers);const v=certificateInputSchema.parse(input);const {data,error}=await createClient().from("supplier_certificates").update({certificate_type:v.certificateType,certificate_number:v.certificateNumber??null,issuing_body:v.issuingBody??null,issue_date:v.issueDate??null,expiry_date:v.expiryDate??null,verification_notes:v.verificationNotes??null,archived_at:v.archivedAt??null}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return certificateDto(data)} export async function archiveSupplierCertificate(organizationId:string,id:string):Promise<SupplierCertificateDTO>{await requireOrganizationRole(organizationId,managers);const {data,error}=await createClient().from("supplier_certificates").update({archived_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("id",id).select().single();fail(error);if(!data)throw new AuthorizationError("ROLE_REQUIRED");return certificateDto(data)}
