begin;
do $$ begin create type public.supplier_status as enum ('active','inactive','suspended','archived'); exception when duplicate_object then null; end $$; do $$ begin create type public.supplier_verification_status as enum ('unverified','under_review','verified','restricted','archived'); exception when duplicate_object then null; end $$; do $$ begin create type public.supplier_legal_entity_type as enum ('company','individual'); exception when duplicate_object then null; end $$; do $$ begin create type public.supplier_capability as enum ('manufacturer','trading_company','broker'); exception when duplicate_object then null; end $$; do $$ begin create type public.supplier_certificate_type as enum ('ISO9001','ISO14001','ISO45001','CE','FDA','SGS','RoHS','BSCI','Sedex','Other'); exception when duplicate_object then null; end $$;
create table public.suppliers (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),supplier_code text not null check(supplier_code~'^[A-Z0-9-]{3,40}$'),legal_name text not null check(char_length(trim(legal_name)) between 1 and 220),display_name text not null check(char_length(trim(display_name)) between 1 and 160),supplier_status public.supplier_status not null default 'active',verification_status public.supplier_verification_status not null default 'unverified',legal_entity_type public.supplier_legal_entity_type not null,website text,email text,phone text,whatsapp text,country_code text check(country_code is null or country_code~'^[A-Z]{2}$'),province text,city text,address text,postal_code text,timezone text,preferred_currency text check(preferred_currency is null or preferred_currency~'^[A-Z]{3}$'),preferred_language text,years_in_business integer check(years_in_business is null or years_in_business>=0),employee_count integer check(employee_count is null or employee_count>=0),annual_capacity_notes text,notes_internal text,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,supplier_code),unique(id,organization_id),check((supplier_status='archived')=(archived_at is not null)));
create table public.supplier_capabilities (supplier_id uuid not null,organization_id uuid not null,capability public.supplier_capability not null,created_at timestamptz not null default now(),primary key(supplier_id,capability),foreign key(supplier_id,organization_id) references public.suppliers(id,organization_id)); create table public.supplier_contacts(id uuid primary key default gen_random_uuid(),supplier_id uuid not null,organization_id uuid not null,name text not null,position text,email text,phone text,whatsapp text,preferred_language text,is_primary boolean not null default false,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(supplier_id,organization_id) references public.suppliers(id,organization_id)); create unique index supplier_contacts_one_primary_idx on public.supplier_contacts(supplier_id) where is_primary and archived_at is null; create table public.supplier_certificates(id uuid primary key default gen_random_uuid(),supplier_id uuid not null,organization_id uuid not null,certificate_type public.supplier_certificate_type not null,certificate_number text,issuing_body text,issue_date date,expiry_date date,verification_notes text,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(supplier_id,organization_id) references public.suppliers(id,organization_id),check(expiry_date is null or issue_date is null or expiry_date>=issue_date));
create trigger suppliers_updated before update on public.suppliers for each row execute procedure public.set_updated_at(); create trigger supplier_contacts_updated before update on public.supplier_contacts for each row execute procedure public.set_updated_at(); create trigger supplier_certificates_updated before update on public.supplier_certificates for each row execute procedure public.set_updated_at();
create or replace function public.is_supplier_manager(org uuid) returns boolean language sql stable security definer set search_path=public as $$select public.has_active_organization_role(org,array['owner','admin','operations']::public.app_role[])$$; create or replace function public.is_supplier_reader(org uuid) returns boolean language sql stable security definer set search_path=public as $$select public.has_active_organization_role(org,array['owner','admin','operations','purchasing','inspection','finance']::public.app_role[])$$;
create or replace function public.replace_supplier_capabilities(target_organization_id uuid, target_supplier_id uuid, selected_capabilities public.supplier_capability[]) returns setof public.supplier_capability language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null then raise exception 'Unauthenticated'; end if;
  if coalesce(cardinality(selected_capabilities),0)=0 then raise exception 'At least one capability is required'; end if;
  if (select count(*) from unnest(selected_capabilities)) <> (select count(distinct capability) from unnest(selected_capabilities) capability) then raise exception 'Duplicate capabilities are not allowed'; end if;
  if not public.is_supplier_manager(target_organization_id) then raise exception 'Supplier capability update is not authorized'; end if;
  if not exists(select 1 from public.suppliers where id=target_supplier_id and organization_id=target_organization_id) then raise exception 'Supplier is not in this organization'; end if;
  delete from public.supplier_capabilities where supplier_id=target_supplier_id and organization_id=target_organization_id and capability <> all(selected_capabilities);
  insert into public.supplier_capabilities(supplier_id,organization_id,capability) select target_supplier_id,target_organization_id,capability from unnest(selected_capabilities) capability on conflict(supplier_id,capability) do nothing;
  return query select capability from public.supplier_capabilities where supplier_id=target_supplier_id and organization_id=target_organization_id order by capability;
end; $$;
revoke execute on function public.replace_supplier_capabilities(uuid,uuid,public.supplier_capability[]) from public,anon; grant execute on function public.replace_supplier_capabilities(uuid,uuid,public.supplier_capability[]) to authenticated;
alter table public.suppliers enable row level security;alter table public.supplier_capabilities enable row level security;alter table public.supplier_contacts enable row level security;alter table public.supplier_certificates enable row level security; revoke all on public.suppliers,public.supplier_capabilities,public.supplier_contacts,public.supplier_certificates from anon,authenticated; grant select,insert,update on public.suppliers,public.supplier_capabilities,public.supplier_contacts,public.supplier_certificates to authenticated;
create policy "supplier read" on public.suppliers for select to authenticated using(public.is_supplier_reader(organization_id));create policy "supplier insert" on public.suppliers for insert to authenticated with check(public.is_supplier_manager(organization_id));create policy "supplier update" on public.suppliers for update to authenticated using(public.is_supplier_manager(organization_id)) with check(public.is_supplier_manager(organization_id));create policy "capability read" on public.supplier_capabilities for select to authenticated using(public.is_supplier_reader(organization_id));create policy "capability insert" on public.supplier_capabilities for insert to authenticated with check(public.is_supplier_manager(organization_id));create policy "capability update" on public.supplier_capabilities for update to authenticated using(public.is_supplier_manager(organization_id)) with check(public.is_supplier_manager(organization_id));create policy "contact read" on public.supplier_contacts for select to authenticated using(public.is_supplier_reader(organization_id));create policy "contact insert" on public.supplier_contacts for insert to authenticated with check(public.is_supplier_manager(organization_id));create policy "contact update" on public.supplier_contacts for update to authenticated using(public.is_supplier_manager(organization_id)) with check(public.is_supplier_manager(organization_id));create policy "certificate read" on public.supplier_certificates for select to authenticated using(public.is_supplier_reader(organization_id));create policy "certificate insert" on public.supplier_certificates for insert to authenticated with check(public.is_supplier_manager(organization_id));create policy "certificate update" on public.supplier_certificates for update to authenticated using(public.is_supplier_manager(organization_id)) with check(public.is_supplier_manager(organization_id));
commit;
