begin;
create or replace function public.complete_supplier_response(target_organization_id uuid,target_supplier_request_id uuid,target_response_type public.supplier_response_type,target_message text,target_received_at timestamptz,target_supplier_contact_id uuid,target_internal_notes text)
returns table(response_id uuid,response_type public.supplier_response_type,response_message text,received_at timestamptz,is_complete_response boolean,request_id uuid,request_status public.supplier_request_status,completed_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$ declare target_candidate uuid; target_item uuid; target_rfq uuid; target_user uuid:=auth.uid(); begin
 if target_user is null then raise exception 'Unauthenticated'; end if; if not public.is_supplier_request_manager(target_organization_id) then raise exception 'Not authorized'; end if;
 select supplier_candidate_id into target_candidate from public.supplier_requests where id=target_supplier_request_id and organization_id=target_organization_id and status not in ('completed','cancelled','archived') for update; if target_candidate is null then raise exception 'Request is not eligible'; end if;
 if target_supplier_contact_id is not null and not exists(select 1 from public.supplier_contacts c join public.supplier_candidates sc on sc.supplier_id=c.supplier_id and sc.organization_id=c.organization_id where c.id=target_supplier_contact_id and sc.id=target_candidate and c.organization_id=target_organization_id) then raise exception 'Supplier contact mismatch'; end if;
 insert into public.supplier_responses(organization_id,supplier_request_id,response_type,message,received_at,received_by_profile_id,supplier_contact_id,is_complete_response,internal_notes) values(target_organization_id,target_supplier_request_id,target_response_type,target_message,coalesce(target_received_at,now()),target_user,target_supplier_contact_id,true,target_internal_notes) returning id,response_type,message,received_at,is_complete_response into response_id,response_type,response_message,received_at,is_complete_response;
 update public.supplier_requests set status='completed',completed_at=now() where id=target_supplier_request_id returning id,status,completed_at into request_id,request_status,completed_at;
 select sc.rfq_item_id into target_item from public.supplier_candidates sc where sc.id=target_candidate; select rfq_id into target_rfq from public.rfq_items where id=target_item and organization_id=target_organization_id;
 insert into public.rfq_activity_events(organization_id,rfq_id,rfq_item_id,event_type,title,visibility,actor_user_id) values(target_organization_id,target_rfq,target_item,'supplier_request_completed','Supplier request completed','internal',target_user);
 return next; end; $$;
revoke execute on function public.complete_supplier_response(uuid,uuid,public.supplier_response_type,text,timestamptz,uuid,text) from public,anon;grant execute on function public.complete_supplier_response(uuid,uuid,public.supplier_response_type,text,timestamptz,uuid,text) to authenticated;
commit;
