begin;
create or replace function public.assert_rfq_attachment_owner() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.owner_type='rfq' and not exists(select 1 from public.rfqs where id=new.owner_id and organization_id=new.organization_id) then raise exception 'Attachment RFQ owner is not in organization'; end if;
 if new.owner_type='rfq_item' and not exists(select 1 from public.rfq_items where id=new.owner_id and organization_id=new.organization_id) then raise exception 'Attachment item owner is not in organization'; end if;
 if new.owner_type='supplier_response' and not exists(select 1 from public.supplier_responses where id=new.owner_id and organization_id=new.organization_id) then raise exception 'Attachment response owner is not in organization'; end if;
 if new.owner_type='quotation' and not exists(select 1 from public.quotations where id=new.owner_id and organization_id=new.organization_id and archived_at is null) then raise exception 'Attachment quotation owner is not in organization'; end if;
 if new.owner_type='purchase_order' and not exists(select 1 from public.purchase_orders where id=new.owner_id and organization_id=new.organization_id and archived_at is null) then raise exception 'Attachment purchase order owner is not in organization'; end if;
 return new; end; $$;

create or replace function public.assert_purchase_order_mutation() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.organization_id is distinct from old.organization_id or new.purchase_order_number is distinct from old.purchase_order_number or new.version_number is distinct from old.version_number or new.rfq_id is distinct from old.rfq_id or new.rfq_item_id is distinct from old.rfq_item_id or new.supplier_id is distinct from old.supplier_id or new.supplier_candidate_id is distinct from old.supplier_candidate_id or new.supplier_selection_id is distinct from old.supplier_selection_id or new.quotation_id is distinct from old.quotation_id or new.currency is distinct from old.currency or new.order_date is distinct from old.order_date then raise exception 'Purchase order identity and commercial source are immutable'; end if;
 if old.status in ('issued','acknowledged','cancelled','superseded','archived') and new is distinct from old and new.status <> 'superseded' then raise exception 'Historical purchase order is immutable'; end if;
 if old.status='approved' and (new.expected_delivery_date is distinct from old.expected_delivery_date or new.incoterm is distinct from old.incoterm or new.payment_terms is distinct from old.payment_terms or new.supplier_reference is distinct from old.supplier_reference or new.supplier_notes is distinct from old.supplier_notes) then raise exception 'Approved purchase order commercial terms require revision'; end if;
 if new.status='approved' and (new.approved_by is null or new.approved_at is null) then raise exception 'Approved purchase order requires approver and timestamp'; end if;
 if new.status='issued' and old.status <> 'approved' then raise exception 'Only approved purchase orders can be issued'; end if;
 if new.status='acknowledged' and old.status <> 'issued' then raise exception 'Only issued purchase orders can be acknowledged'; end if;
 if new.status='cancelled' and new.cancelled_at is null then raise exception 'Cancelled purchase order requires timestamp'; end if;
 return new; end; $$;
create trigger purchase_orders_validate_mutation before update on public.purchase_orders for each row execute procedure public.assert_purchase_order_mutation();
create or replace function public.assert_purchase_order_item_mutation() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if not exists(select 1 from public.purchase_orders p where p.id=new.purchase_order_id and p.organization_id=new.organization_id and p.status='draft' and p.archived_at is null) then raise exception 'Purchase order items are editable only while the purchase order is draft'; end if; return new; end; $$;
create trigger purchase_order_items_validate_mutation before insert or update on public.purchase_order_items for each row execute procedure public.assert_purchase_order_item_mutation();

create or replace function public.create_purchase_order_from_selection(target_organization_id uuid,target_supplier_selection_id uuid,target_order_date date,target_expected_delivery_date date,target_supplier_reference text,target_internal_notes text,target_supplier_notes text)
returns setof public.purchase_orders language plpgsql security definer set search_path=public,auth as $$
declare s public.supplier_selections; q public.quotations; created_po public.purchase_orders; item_count integer;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if; if not public.has_active_organization_role(target_organization_id,array['owner','admin','operations','purchasing']::public.app_role[]) then raise exception 'Purchase order management role required'; end if;
 select * into s from public.supplier_selections where id=target_supplier_selection_id and organization_id=target_organization_id and status='active'; if s.id is null then raise exception 'Active supplier selection is required'; end if;
 select * into q from public.quotations where id=s.quotation_id and organization_id=target_organization_id and rfq_id=s.rfq_id and rfq_item_id=s.rfq_item_id and supplier_id=s.supplier_id and supplier_candidate_id=s.supplier_candidate_id and archived_at is null and status in ('received','under_review','accepted'); if q.id is null then raise exception 'Selected quotation is not eligible'; end if;
 if target_expected_delivery_date is not null and target_expected_delivery_date<target_order_date then raise exception 'Expected delivery date precedes order date'; end if;
 perform pg_advisory_xact_lock(hashtext(target_organization_id::text||':'||target_supplier_selection_id::text)); if exists(select 1 from public.purchase_orders p where p.organization_id=target_organization_id and p.supplier_selection_id=s.id and p.status in ('draft','approved','issued','acknowledged')) then raise exception 'Current purchase order already exists for selection'; end if;
 select count(*) into item_count from public.quotation_items where organization_id=target_organization_id and quotation_id=q.id and rfq_item_id=s.rfq_item_id; if item_count=0 then raise exception 'Selected quotation has no orderable quotation items'; end if;
 insert into public.purchase_orders(organization_id,purchase_order_number,version_number,rfq_id,rfq_item_id,supplier_id,supplier_candidate_id,supplier_selection_id,quotation_id,currency,order_date,expected_delivery_date,incoterm,payment_terms,supplier_reference,internal_notes,supplier_notes,created_by) values(target_organization_id,public.generate_purchase_order_number(),1,s.rfq_id,s.rfq_item_id,s.supplier_id,s.supplier_candidate_id,s.id,q.id,q.currency,target_order_date,target_expected_delivery_date,q.incoterm,q.payment_terms,target_supplier_reference,target_internal_notes,target_supplier_notes,auth.uid()) returning * into created_po;
 insert into public.purchase_order_items(organization_id,purchase_order_id,rfq_item_id,quotation_item_id,quantity,unit,unit_price,currency,product_description,moq,agreed_lead_time_days,packaging_notes,supplier_notes,internal_notes) select target_organization_id,created_po.id,qi.rfq_item_id,qi.id,qi.quantity,qi.unit,qi.unit_price,q.currency,coalesce(ri.product_name,qi.notes),qi.moq,coalesce(qi.lead_time_days,q.lead_time_days),qi.packaging_info,null,qi.notes from public.quotation_items qi join public.rfq_items ri on ri.id=qi.rfq_item_id and ri.organization_id=qi.organization_id where qi.organization_id=target_organization_id and qi.quotation_id=q.id and qi.rfq_item_id=s.rfq_item_id;
 insert into public.rfq_activity_events(organization_id,rfq_id,rfq_item_id,event_type,title,visibility,actor_user_id,metadata) values(target_organization_id,s.rfq_id,s.rfq_item_id,'purchase_order_created','Purchase order created','internal',auth.uid(),jsonb_build_object('purchase_order_id',created_po.id,'purchase_order_number',created_po.purchase_order_number)); return next created_po;
end; $$;
create or replace function public.create_purchase_order_revision(target_organization_id uuid,target_purchase_order_id uuid,target_internal_notes text,target_supplier_notes text)
returns setof public.purchase_orders language plpgsql security definer set search_path=public,auth as $$
declare previous_po public.purchase_orders; revised_po public.purchase_orders; next_version integer;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if; if not public.has_active_organization_role(target_organization_id,array['owner','admin','operations','purchasing']::public.app_role[]) then raise exception 'Purchase order management role required'; end if;
 select * into previous_po from public.purchase_orders where id=target_purchase_order_id and organization_id=target_organization_id and status in ('draft','approved','issued','acknowledged'); if previous_po.id is null then raise exception 'Current purchase order was not found'; end if;
 perform pg_advisory_xact_lock(hashtext(target_organization_id::text||':'||previous_po.purchase_order_number)); select coalesce(max(version_number),0)+1 into next_version from public.purchase_orders where organization_id=target_organization_id and purchase_order_number=previous_po.purchase_order_number;
 update public.purchase_orders set status='superseded' where id=previous_po.id and organization_id=target_organization_id;
 insert into public.purchase_orders(organization_id,purchase_order_number,version_number,rfq_id,rfq_item_id,supplier_id,supplier_candidate_id,supplier_selection_id,quotation_id,currency,order_date,expected_delivery_date,incoterm,payment_terms,supplier_reference,internal_notes,supplier_notes,created_by) values(target_organization_id,previous_po.purchase_order_number,next_version,previous_po.rfq_id,previous_po.rfq_item_id,previous_po.supplier_id,previous_po.supplier_candidate_id,previous_po.supplier_selection_id,previous_po.quotation_id,previous_po.currency,current_date,previous_po.expected_delivery_date,previous_po.incoterm,previous_po.payment_terms,previous_po.supplier_reference,target_internal_notes,target_supplier_notes,auth.uid()) returning * into revised_po;
 insert into public.purchase_order_items(organization_id,purchase_order_id,rfq_item_id,quotation_item_id,quantity,unit,unit_price,currency,product_description,moq,agreed_lead_time_days,packaging_notes,supplier_notes,internal_notes) select organization_id,revised_po.id,rfq_item_id,quotation_item_id,quantity,unit,unit_price,currency,product_description,moq,agreed_lead_time_days,packaging_notes,supplier_notes,internal_notes from public.purchase_order_items where purchase_order_id=previous_po.id and organization_id=target_organization_id and archived_at is null;
 insert into public.rfq_activity_events(organization_id,rfq_id,rfq_item_id,event_type,title,visibility,actor_user_id,metadata) values(target_organization_id,revised_po.rfq_id,revised_po.rfq_item_id,'purchase_order_revised','Purchase order revised','internal',auth.uid(),jsonb_build_object('previous_purchase_order_id',previous_po.id,'purchase_order_id',revised_po.id,'version_number',next_version)); return next revised_po;
end; $$;
revoke all on function public.create_purchase_order_from_selection(uuid,uuid,date,date,text,text,text),public.create_purchase_order_revision(uuid,uuid,text,text) from public,anon; grant execute on function public.create_purchase_order_from_selection(uuid,uuid,date,date,text,text,text),public.create_purchase_order_revision(uuid,uuid,text,text) to authenticated;
commit;
