begin;
do $$ begin create type public.purchase_order_status as enum ('draft','approved','issued','acknowledged','cancelled','superseded','archived'); exception when duplicate_object then null; end $$;
create or replace function public.generate_purchase_order_number() returns text language sql volatile set search_path=public as $$ select 'KC-PO-' || to_char(timezone('utc',now()),'YYYY') || '-' || upper(substr(encode(gen_random_bytes(5),'hex'),1,8)) $$;
create table public.purchase_orders(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
 purchase_order_number text not null default public.generate_purchase_order_number() check(purchase_order_number~'^KC-PO-[0-9]{4}-[A-Z0-9]{8}$'), version_number integer not null check(version_number>0),
 rfq_id uuid not null, rfq_item_id uuid not null, supplier_id uuid not null, supplier_candidate_id uuid not null, supplier_selection_id uuid not null, quotation_id uuid not null,
 status public.purchase_order_status not null default 'draft', currency text not null check(currency~'^[A-Z]{3}$'), order_date date not null default current_date, expected_delivery_date date,
 incoterm text check(incoterm is null or incoterm~'^[A-Z]{3}$'), payment_terms text, supplier_reference text, internal_notes text, supplier_notes text,
 created_by uuid not null references public.profiles(id) on delete restrict, approved_by uuid references public.profiles(id) on delete restrict, approved_at timestamptz, cancelled_at timestamptz, archived_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(purchase_order_number,version_number), unique(id,organization_id),
 foreign key(rfq_item_id,organization_id) references public.rfq_items(id,organization_id), foreign key(supplier_id,organization_id) references public.suppliers(id,organization_id), foreign key(supplier_candidate_id,organization_id) references public.supplier_candidates(id,organization_id), foreign key(supplier_selection_id,organization_id) references public.supplier_selections(id,organization_id), foreign key(quotation_id,organization_id) references public.quotations(id,organization_id),
 check(expected_delivery_date is null or expected_delivery_date>=order_date), check((status='approved')=(approved_at is not null)), check((status='cancelled')=(cancelled_at is not null)), check((status='archived')=(archived_at is not null))
);
create table public.purchase_order_items(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null, purchase_order_id uuid not null, rfq_item_id uuid not null, quotation_item_id uuid,
 quantity numeric(18,3) not null check(quantity>0), unit text not null check(char_length(trim(unit)) between 1 and 40), unit_price numeric(18,3) not null check(unit_price>=0), currency text not null check(currency~'^[A-Z]{3}$'), line_total numeric(18,3) generated always as(quantity*unit_price) stored,
 product_description text, moq numeric(18,3) check(moq is null or moq>0), agreed_lead_time_days integer check(agreed_lead_time_days is null or agreed_lead_time_days>=0), packaging_notes text, supplier_notes text, internal_notes text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(purchase_order_id,organization_id) references public.purchase_orders(id,organization_id), foreign key(rfq_item_id,organization_id) references public.rfq_items(id,organization_id), foreign key(quotation_item_id) references public.quotation_items(id)
);
create trigger purchase_orders_updated before update on public.purchase_orders for each row execute procedure public.set_updated_at(); create trigger purchase_order_items_updated before update on public.purchase_order_items for each row execute procedure public.set_updated_at();
create or replace function public.is_purchase_order_manager(org uuid) returns boolean language sql stable security definer set search_path=public as $$select public.has_active_organization_role(org,array['owner','admin','operations','purchasing']::public.app_role[])$$;
create or replace function public.is_purchase_order_reader(org uuid) returns boolean language sql stable security definer set search_path=public as $$select public.has_active_organization_role(org,array['owner','admin','operations','purchasing','inspection','finance']::public.app_role[])$$;
alter table public.purchase_orders enable row level security; alter table public.purchase_order_items enable row level security; revoke all on public.purchase_orders,public.purchase_order_items from anon,authenticated; grant select,update on public.purchase_orders to authenticated; grant select,insert,update on public.purchase_order_items to authenticated;
create policy "purchase order read" on public.purchase_orders for select to authenticated using(public.is_purchase_order_reader(organization_id)); create policy "purchase order update" on public.purchase_orders for update to authenticated using(public.is_purchase_order_manager(organization_id)) with check(public.is_purchase_order_manager(organization_id));
create policy "purchase order item read" on public.purchase_order_items for select to authenticated using(public.is_purchase_order_reader(organization_id)); create policy "purchase order item insert" on public.purchase_order_items for insert to authenticated with check(public.is_purchase_order_manager(organization_id)); create policy "purchase order item update" on public.purchase_order_items for update to authenticated using(public.is_purchase_order_manager(organization_id)) with check(public.is_purchase_order_manager(organization_id));
commit;
