import "server-only";
import { AuthorizationError, getAuthenticatedUserId, requireOrganizationRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import type { AppRole, Database } from "@/lib/supabase/types";
import { activityInputSchema, attachmentInputSchema, rfqInputSchema, rfqItemInputSchema, type ActivityInput, type AttachmentInput, type RfqInput, type RfqItemInput } from "./validation";
import type { CustomerSafeActivity, CustomerSafeAttachment, CustomerSafeRfq, CustomerSafeRfqItem } from "./authorization";

const MANAGERS: readonly AppRole[] = ["owner", "admin", "operations"];
const READERS: readonly AppRole[] = [...MANAGERS, "purchasing", "inspection", "finance"];
type Rfq = Database["public"]["Tables"]["rfqs"]["Row"]; type Item = Database["public"]["Tables"]["rfq_items"]["Row"];
async function manager(org: string) { return requireOrganizationRole(org, MANAGERS); }

export async function createRfq(organizationId: string, input: RfqInput): Promise<Rfq> { await manager(organizationId); const user = await getAuthenticatedUserId(); if (!user) throw new AuthorizationError("UNAUTHENTICATED"); const v = rfqInputSchema.parse(input); const { data, error } = await createClient().from("rfqs").insert({ organization_id: organizationId, customer_id: v.customerId, primary_contact_id: v.primaryContactId ?? null, title: v.title, description: v.description ?? null, status: v.status, priority: v.priority, source: v.source ?? null, preferred_currency: v.preferredCurrency ?? null, destination_country_code: v.destinationCountryCode ?? null, destination_city: v.destinationCity ?? null, target_date: v.targetDate ?? null, assigned_to: v.assignedTo ?? null, created_by: user, archived_at: v.status === "archived" ? new Date().toISOString() : null }).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function updateRfq(organizationId: string, id: string, input: RfqInput): Promise<Rfq> { await manager(organizationId); const v = rfqInputSchema.parse(input); const { data, error } = await createClient().from("rfqs").update({ title: v.title, description: v.description ?? null, status: v.status, priority: v.priority, source: v.source ?? null, preferred_currency: v.preferredCurrency ?? null, destination_country_code: v.destinationCountryCode ?? null, destination_city: v.destinationCity ?? null, target_date: v.targetDate ?? null, assigned_to: v.assignedTo ?? null, archived_at: v.status === "archived" ? new Date().toISOString() : null }).eq("id", id).eq("organization_id", organizationId).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function archiveRfq(organizationId: string, id: string) { await manager(organizationId); return createClient().from("rfqs").update({ status: "archived", archived_at: new Date().toISOString() }).eq("id", id).eq("organization_id", organizationId).select().single(); }
export async function createRfqItem(organizationId: string, rfqId: string, input: RfqItemInput): Promise<Item> { await manager(organizationId); const user = await getAuthenticatedUserId(); if (!user) throw new AuthorizationError("UNAUTHENTICATED"); const v = rfqItemInputSchema.parse(input); const { data, error } = await createClient().from("rfq_items").insert({ organization_id: organizationId, rfq_id: rfqId, item_number: v.itemNumber, product_name: v.productName, description: v.description ?? null, specifications: v.specifications ?? null, requested_quantity: v.requestedQuantity, unit: v.unit, target_unit_price: v.targetUnitPrice ?? null, target_currency: v.targetCurrency ?? null, target_moq: v.targetMoq ?? null, target_lead_time_days: v.targetLeadTimeDays ?? null, customization_required: v.customizationRequired, branding_required: v.brandingRequired, packaging_required: v.packagingRequired, sample_required: v.sampleRequired, status: v.status, priority: v.priority, customer_notes: v.customerNotes ?? null, internal_notes: v.internalNotes ?? null, created_by: user, archived_at: v.status === "archived" ? new Date().toISOString() : null }).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function updateRfqItem(organizationId: string, id: string, input: RfqItemInput): Promise<Item> { await manager(organizationId); const v = rfqItemInputSchema.parse(input); const { data, error } = await createClient().from("rfq_items").update({ product_name:v.productName, description:v.description ?? null, specifications:v.specifications ?? null, requested_quantity:v.requestedQuantity, unit:v.unit, target_unit_price:v.targetUnitPrice ?? null, target_currency:v.targetCurrency ?? null, target_moq:v.targetMoq ?? null, target_lead_time_days:v.targetLeadTimeDays ?? null, customization_required:v.customizationRequired, branding_required:v.brandingRequired, packaging_required:v.packagingRequired, sample_required:v.sampleRequired, status:v.status, priority:v.priority, customer_notes:v.customerNotes ?? null, internal_notes:v.internalNotes ?? null, archived_at:v.status === "archived" ? new Date().toISOString() : null }).eq("id", id).eq("organization_id", organizationId).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function archiveRfqItem(organizationId: string, id: string) { await manager(organizationId); return createClient().from("rfq_items").update({ status:"archived", archived_at:new Date().toISOString() }).eq("id", id).eq("organization_id", organizationId).select().single(); }
export async function listOrganizationRfqs(organizationId: string): Promise<Rfq[]> { await requireOrganizationRole(organizationId, READERS); const { data, error } = await createClient().from("rfqs").select().eq("organization_id", organizationId).is("archived_at", null); if (error) throw new AuthorizationError("ROLE_REQUIRED"); return data ?? []; }
export async function addRfqAttachment(organizationId: string, input: AttachmentInput) { await manager(organizationId); const user = await getAuthenticatedUserId(); if (!user) throw new AuthorizationError("UNAUTHENTICATED"); const v = attachmentInputSchema.parse(input); const { data, error } = await createClient().from("rfq_attachments").insert({ organization_id: organizationId, owner_type: v.ownerType, owner_id: v.ownerId, storage_bucket: v.storageBucket, storage_path: v.storagePath, original_filename: v.originalFilename, content_type: v.contentType, file_size: v.fileSize, visibility: v.visibility, uploaded_by: user }).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function archiveRfqAttachment(organizationId: string, id: string) { await manager(organizationId); const { data, error } = await createClient().from("rfq_attachments").update({ archived_at:new Date().toISOString() }).eq("id", id).eq("organization_id", organizationId).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function appendRfqActivity(organizationId: string, rfqId: string, input: ActivityInput) { await manager(organizationId); const user = await getAuthenticatedUserId(); if (!user) throw new AuthorizationError("UNAUTHENTICATED"); const v = activityInputSchema.parse(input); const { data, error } = await createClient().from("rfq_activity_events").insert({ organization_id: organizationId, rfq_id: rfqId, rfq_item_id: v.rfqItemId ?? null, event_type: v.eventType, title: v.title, description: v.description ?? null, visibility: v.visibility, metadata: v.metadata ?? null, actor_user_id: user }).select().single(); if (error || !data) throw new AuthorizationError("ROLE_REQUIRED"); return data; }
export async function getMyCustomerRfqs(): Promise<CustomerSafeRfq[]> { const { data, error } = await createClient().rpc("get_my_rfq_workspaces"); if (error) throw new AuthorizationError("MEMBERSHIP_REQUIRED"); return (data ?? []).map(r => ({ id:r.id, publicReference:r.public_reference, title:r.title, description:r.description, status:r.status, priority:r.priority, preferredCurrency:r.preferred_currency, destinationCountryCode:r.destination_country_code, destinationCity:r.destination_city, targetDate:r.target_date, submittedAt:r.submitted_at, closedAt:r.closed_at, createdAt:r.created_at })); }
export async function getMyCustomerRfqItems(rfqId: string): Promise<CustomerSafeRfqItem[]> { const { data, error } = await createClient().rpc("get_my_rfq_items", { target_rfq_id: rfqId }); if (error) throw new AuthorizationError("MEMBERSHIP_REQUIRED"); return (data ?? []).map(i => ({ id:i.id,itemNumber:i.item_number,productName:i.product_name,description:i.description,specifications:i.specifications,requestedQuantity:Number(i.requested_quantity),unit:i.unit,targetUnitPrice:i.target_unit_price === null ? null : Number(i.target_unit_price),targetCurrency:i.target_currency,targetMoq:i.target_moq === null ? null : Number(i.target_moq),targetLeadTimeDays:i.target_lead_time_days,customizationRequired:i.customization_required,brandingRequired:i.branding_required,packagingRequired:i.packaging_required,sampleRequired:i.sample_required,status:i.status,priority:i.priority,customerNotes:i.customer_notes,createdAt:i.created_at })); }
export async function getMyCustomerRfqAttachments(rfqId: string): Promise<CustomerSafeAttachment[]> { const { data, error } = await createClient().rpc("get_my_rfq_attachments", { target_rfq_id: rfqId }); if (error) throw new AuthorizationError("MEMBERSHIP_REQUIRED"); return (data ?? []).map(a => ({ id:a.id,ownerType:a.owner_type,ownerId:a.owner_id,originalFilename:a.original_filename,contentType:a.content_type,fileSize:Number(a.file_size),createdAt:a.created_at })); }
export async function getMyCustomerRfqActivity(rfqId: string): Promise<CustomerSafeActivity[]> { const { data, error } = await createClient().rpc("get_my_rfq_activity", { target_rfq_id: rfqId }); if (error) throw new AuthorizationError("MEMBERSHIP_REQUIRED"); return (data ?? []).map(e => ({ id:e.id,rfqItemId:e.rfq_item_id,eventType:e.event_type,title:e.title,description:e.description,occurredAt:e.occurred_at })); }
