import { z } from "zod";

export const RFQ_STATUSES = ["draft", "submitted", "under_review", "sourcing", "awaiting_customer", "approved", "cancelled", "completed", "archived"] as const;
export const RFQ_ITEM_STATUSES = ["draft", "ready_for_sourcing", "sourcing", "awaiting_information", "shortlisted", "selected", "cancelled", "completed", "archived"] as const;
export const RFQ_PRIORITIES = ["low", "normal", "high", "urgent"] as const;
export const ATTACHMENT_OWNER_TYPES = ["rfq", "rfq_item", "supplier_response"] as const;
export const VISIBILITIES = ["internal", "customer"] as const;
export const ACTIVITY_EVENT_TYPES = ["rfq_created", "rfq_submitted", "rfq_status_changed", "rfq_updated", "rfq_item_created", "rfq_item_updated", "rfq_item_status_changed", "attachment_added", "attachment_archived", "supplier_request_created", "supplier_request_sent", "supplier_response_received", "supplier_request_completed", "supplier_request_cancelled"] as const;
const text = (max: number) => z.string().trim().max(max).transform(value => value || undefined).optional();
const uuid = z.string().uuid();
const decimal = z.number().finite().positive();

export const rfqInputSchema = z.object({ customerId: uuid, primaryContactId: uuid.optional(), title: z.string().trim().min(1).max(180), description: text(4000), status: z.enum(RFQ_STATUSES).default("draft"), priority: z.enum(RFQ_PRIORITIES).default("normal"), source: text(100), preferredCurrency: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).optional(), destinationCountryCode: z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).optional(), destinationCity: text(120), targetDate: z.string().date().optional(), assignedTo: uuid.optional() });
export const rfqItemInputSchema = z.object({ itemNumber: z.number().int().positive(), productName: z.string().trim().min(1).max(240), description: text(4000), specifications: text(8000), requestedQuantity: decimal, unit: z.string().trim().min(1).max(40), targetUnitPrice: z.number().finite().nonnegative().optional(), targetCurrency: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).optional(), targetMoq: decimal.optional(), targetLeadTimeDays: z.number().int().nonnegative().optional(), customizationRequired: z.boolean().default(false), brandingRequired: z.boolean().default(false), packagingRequired: z.boolean().default(false), sampleRequired: z.boolean().default(false), status: z.enum(RFQ_ITEM_STATUSES).default("draft"), priority: z.enum(RFQ_PRIORITIES).default("normal"), customerNotes: text(4000), internalNotes: text(4000) });
export const attachmentInputSchema = z.object({ ownerType: z.enum(ATTACHMENT_OWNER_TYPES), ownerId: uuid, storageBucket: z.string().regex(/^[a-z0-9][a-z0-9-]{0,62}$/), storagePath: z.string().min(1).max(1024).refine(value => !value.startsWith("/")), originalFilename: z.string().trim().min(1).max(255), contentType: z.string().trim().min(1).max(160), fileSize: z.number().int().positive().max(104857600), visibility: z.enum(VISIBILITIES).default("internal") });
const supplierRequestActivityTypes = ["supplier_request_created", "supplier_request_sent", "supplier_response_received", "supplier_request_completed", "supplier_request_cancelled"] as const;
export const activityInputSchema = z.object({ rfqItemId: uuid.optional(), eventType: z.enum(ACTIVITY_EVENT_TYPES), title: z.string().trim().min(1).max(240), description: text(4000), visibility: z.enum(VISIBILITIES).default("internal"), metadata: z.record(z.string(), z.unknown()).optional().refine(value => !value || JSON.stringify(value).length <= 8192, "Metadata is too large") }).superRefine((value, context) => { if (supplierRequestActivityTypes.includes(value.eventType as typeof supplierRequestActivityTypes[number]) && value.visibility !== "internal") context.addIssue({ code: z.ZodIssueCode.custom, message: "Supplier request events must remain internal" }); });
export type RfqInput = z.infer<typeof rfqInputSchema>; export type RfqItemInput = z.infer<typeof rfqItemInputSchema>; export type AttachmentInput = z.infer<typeof attachmentInputSchema>; export type ActivityInput = z.infer<typeof activityInputSchema>;
